### ISSUE TITLE
is it tested on redmine 2.3.2 ?

### ISSUE THREAD

**Issue by cforce** [zhijie/redmine-mobile#6]

**Comment by zhijie** [comment]
Noop. However, according to Redmine REST api doc(http://www.redmine.org/projects/redmine/wiki/Rest_api), current project should be compatible with 2.3.2

**Comment by CodeXey** [comment]
你好，这个项目不维护了吗？我现在用它连接地址但总是失败，随后刷新会crash。

**Comment by zhijie** [comment]
非常抱歉 已经停止维护了

**Comment by CodeXey** [comment]
got it

**Comment by cforce** [comment]
Great .. we are now at 3.2.1 - somhow too late
